### ISSUE TITLE
Site Not Found

### ISSUE THREAD

**Issue by lectykim** [kheeyaa/dev-jeans#1]
Hey devhee, your hosting has stoped. 
It looks like a Firebase server error.
Can you fix it?
below is the error code.

Site Not Found
Why am I seeing this?
There are a few potential reasons:

You haven't deployed an app yet.
You may have deployed an empty directory.
This is a custom domain, but we haven't finished setting it up yet.
How can I deploy my first app?
Refer to our [hosting documentation](https://firebase.google.com/docs/hosting/) to get started.

**Comment by kheeyaa** [comment]
You can visit now dev-jeans site. thank you.
https://dev-jeans-9f478.web.app/
